[package]
name = "rusculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
egui = "=0.27.2"
eframe = "= 0.27.2"
image = "0.24" 
